### PR TITLE
BUG: Use yield from in Win32AsyncioEventLoop

### PR DESCRIPTION
**Pull request by eric-wieser**
The previous code was not correct, as `yield from` also pushes exceptions to the iterator, which this did not.

This pattern is already used elsewhere

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @eric-wieser,

Thank you for the pull request. The ``exec_`` is not going to do a lot without catching a ``SyntaxError``.

This is one of the things that should have been fixed on the 2.0 branch already. I consider that the way forward. Honestly, I prefer not to do big changes anymore on this branch, unless important or obvious bug fixes. Especially the event loop is easy to get wrong, and actually there are more asyncio related bugs on this 1.0 branch. Hopefully that's fine.

**Comment by eric-wieser** [comment]
> The exec_ is not going to do a lot without catching a SyntaxError.

Oops, you're right - I forgot this was in a class suite, not a function one.

I was not aware of the 2.0.0 branch.

One thing I'm puzzled by - this file has a `import asyncio` at the global level. Does that not mean that it can use `yield from` directly, as it would `ImportError` anyway?

**Comment by eric-wieser** [comment]
(And you're correct, this is fixed in the 2.0 tree)

**Comment by jonathanslenders** [comment]
Assuming I can close this. Let me know if that's not the case.

**Pull request closed without merging**
