### PR TITLE
lazy pkg_resources import

### PR DESCRIPTION
**Pull request by scopatz**
This implements a background `pkg_resources` import when using pygments.

Hopefully, some of the other lazy tools here can also be used to speed up prompt-toolkit startup as well.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @scopatz,

This is a change that I prefer not to include in prompt-toolkit itself. One reason is that many users are import pygments themselves, and we can't be sure that our imports are the first one. Further, it's an ugly workaround for something that has to be fixed in Pygments itself.

Is it correct that calling ``load_module_in_background`` outside of prompt-toolkit, but at the very beginning of the application would be sufficient to get the speedup?

btw, the latest master branch should now have a few other speedups in the key bindings that you could appreciate.

Jonathan

**Comment by scopatz** [comment]
> One reason is that many users are import pygments themselves, and we can't be sure that our imports are the first one. 

Sure, in which case this code will simply fall back to the previous import.

> Further, it's an ugly workaround for something that has to be fixed in Pygments itself.

I agree that the fix is deeper down the stack.  If not pygments, it should be in pkg_resources or setuptools.  I don't have a lot of confidence that this will be fixed ever though, which is what led me to this solution.  I think the benefits to the users offset the cost of a relatively small amount of ugliness.

> Is it correct that calling load_module_in_background outside of prompt-toolkit, but at the very beginning of the application would be sufficient to get the speedup?

Yes it is.  I just figured that this also affecting all other prompt-toolkit project and thus helps perpetuate the myth that Python has to be slow.  It is totally fine if you don't feel this is appropriate; was just a suggestion. 

I would appreciate it, though, if other people hit this slow import issue, if you would point them to this solution.  I am planning on splitting lazyasd into its own package, so that other people can use it without xonsh.

> btw, the latest master branch should now have a few other speedups in the key bindings that you could appreciate.

Awesome!

**Comment by jonathanslenders** [comment]
I'm closing this. Prompt_toolkit 2.0 doesn't require Pygments anymore. So, by default it won't import pkg_resources at all during start up.
Let me know if I'm missing something that would still require something like this for Xonsh.

**Comment by scopatz** [comment]
Thanks for pushing through with this.

**Comment by scopatz** [comment]
Glad that pygments is no longer a requirement.

**Pull request closed without merging**
