### PR TITLE
2.0: renamed default_style to default_ui_style.

### PR DESCRIPTION
**Pull request by j-bennet**
Fixed some full-screen examples (`default_style` does not exist anymore).

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @j-bennet, thanks for noticing this!
Actually, the right fix would be to not include ``default_ui_style`` at all. It is already included in any application by default. So, if you want, you can also remove the ``merge_styles`` function in these examples.

**Comment by j-bennet** [comment]
@jonathanslenders Good to know! I'll change that.

**Comment by j-bennet** [comment]
@jonathanslenders Changed.

**Comment by jonathanslenders** [comment]
Thanks!

**Comment by jonathanslenders** [comment]
Thanks!

**Pull request merged**
