### PR TITLE
Implement Emacs Meta-. key binding (insert last word)

### PR DESCRIPTION
**Pull request by mbachry**
Now when IPython uses prompt_toolkit, I miss readline's `Meta-.` keybinding a lot. Here's my attempt to implement it.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Thank you for this @mbachry,
I need some time to review these changes, but it sounds very useful!
Jonathan

**Comment by adamchainz** [comment]
This would be related to #343

**Comment by jonathanslenders** [comment]
Hi @mbachry,

I combined both pull request in the following commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c09bf034aeeb2facbfbc070cc4fa2f58620baa5

If you have time, could you have a look and see whether this implements all you need?

Thanks again for all the effort!
Jonathan

**Comment by jonathanslenders** [comment]
Unit tests were merged here: https://github.com/jonathanslenders/python-prompt-toolkit/commit/c8e1547e37689708725e0d01a6c24501f5664722 (with a few small changes.)

Thanks for that!

**Comment by mbachry** [comment]
I checked current master and it works great for me. Thanks!

**Comment by adamchainz** [comment]
Works for me! Thanks.

**Pull request closed without merging**
