### PR TITLE
Support for ZeroWidthEscape tokens in prompt and token lists. Used to…

### PR DESCRIPTION
**Pull request by jonathanslenders**
… support final term escapes.

### CODE REVIEW

**Comment by Carreau** [comment]
Nop, does not seem to work for me:

```
$ ipython
Python 3.5.1 |Anaconda custom (x86_64)| (default, Dec  7 2015, 11:24:55)
Type "copyright", "credits" or "license" for more information.

IPython 5.0.0.dev -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from iterm2_tools.shell_integration import BEFORE_PROMPT, AFTER_PROMPT

In [2]: from IPython.terminal.prompts import Prompts, Token
In [3]: import os
   ...: class MyPrompt(Prompts):
   ...:     def in_prompt_tokens(self, cli=None):
   ...:         return [ ( Token.ZeroWidthEscape, BEFORE_PROMPT),(Token, os.getcwd()), (Token.Prompt, '>>>'), (Token.ZeroWidthEscape, AFTER_PROMPT)]
In [4]: ip = get_ipython()
In [5]: ip.prompts = MyPrompt(ip)

/Users/bussonniermatthias/dev/ipython>>>            # cursor is ofset.
/Users/bussonniermatthias/dev/ipython>>>
```

screen shot 2016-05-27 at 14 28 29


Using this PR commit,  and ipython/ipython#9471 bu tI have to run now, so I might just have done something wrong.

**Comment by Carreau** [comment]
(note, the escape sequences are working as I have the small indicator at the beginning of the line.)

**Comment by Carreau** [comment]
Ok, the the error appear only when `multiline=True` is set.

**Comment by Carreau** [comment]
Made a PR against your PR, that seem to fix thing for me.

**Comment by Carreau** [comment]
+1, works for me.

**Comment by Carreau** [comment]
Can you export `Token.ZeroWidthEscape` somewhere ?  I know it's a dummy object, but that would help to test whether the functionality is available (and import would avoid Typos)

**Comment by jonathanslenders** [comment]
I'll export ``Token.ZerowidthEscape`` and then I'll merge everything into master.

**Comment by Carreau** [comment]
> I'll export Token.ZerowidthEscape and then I'll merge everything into master.

Great !

**Comment by jonathanslenders** [comment]
Merged into master and available here: 
https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/token.py#L44

**Comment by Carreau** [comment]
Great Thanks !

**Comment by Carreau** [comment]
@jonathanslenders will master become 1.1 or 2.x ?

cc @takluyver.

**Pull request merged**
