### PR TITLE
Added Emacs mode Meta-. binding 'yank last arg'

### LINKED ISSUE #343: Implement readline's `yank-last-arg`
The implementation of readline's `yank-last-arg` command [is currently a TODO](https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/emacs.py#L298). It would be good for it to actually get implemented!

### PR DESCRIPTION
**Pull request by adamchainz**
Fixes #343. Alternative implementation to #336 that uses a single function and also implements `yank-nth-arg`, in the same style as readline.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @adamchainz,

Cool! Thanks a lot for this.
I still need to take some time to compare this implementation and the other.
Probably, I'd like to go for a solution where the key bindings are completely stateless, and the state is stored in the ``Buffer`` object. (Need to think about this.)

Jonathan

**Comment by adamchainz** [comment]
Happy to change that but I thought it was rather elegant that it can all be done with function-bound 'static' variables 😄

**Comment by jonathanslenders** [comment]
Hi @adamchainz,

I combined both pull request in the following commit: https://github.com/jonathanslenders/python-prompt-toolkit/commit/0c09bf034aeeb2facbfbc070cc4fa2f58620baa5

If you have time, could you have a look and see whether this implements all you need?

Thanks,
Jonathan

**Comment by adamchainz** [comment]
Thanks! Sure, will do this evening.

**Pull request closed without merging**
