### PR TITLE
Path completer tests and expand user

### LINKED ISSUE #170: Cannot get expanduser to work with PathCompleter
Using this minimal snippet:
```

from __future__ import unicode_literals
from __future__ import print_function
from prompt_toolkit.contrib.completers.filesystem import PathCompleter
from prompt_toolkit.shortcuts import get_input

def main():
    completer = PathCompleter(only_directories=False, expanduser=True)
    while True:
        try:
            text = get_input('path> ', completer=completer)
        except EOFError:
            break
        except KeyboardInterrupt:
            continue
        if text and text.strip():
            print('You selected: ', text)

if __name__ == '__main__':
    main()
```
I fire the script and start typing `~/` and I get no completion at all...
Typing tab completes on the path of os.cwd alright.
I am getting something wrong to get exxpanduser to work?

I think this is missing a test and possibly something like that about there:
https://github.com/jonathanslenders/python-prompt-toolkit/blob/c7c306bc5ca57beff9a64150eb86b7d75453ab48/prompt_toolkit/contrib/completers/filesystem.py#L45
```
if self.expanduser:
    text = os.path.expanduser(text)
```

### PR DESCRIPTION
**Pull request by pombredanne**
@jonathanslenders 
This PR adds tests for the PathCompleter and fixes #170 
It replaces #171 which I am closing now.

### CODE REVIEW

**Comment by pombredanne** [comment]
@jonathanslenders After some laborious fixes of the Python 2/3 unicode issues, this PR is clean now. I can squash the commits in one if you prefer this.

**Comment by pombredanne** [comment]
@jonathanslenders any feedback?

**Comment by jonathanslenders** [comment]
Yes, sorry about the delay. I've not had the time yet to reply.

This looks good to me. I'm going to merge it. Don't worry about the squashing, I'll do that.

Thanks a lot! Also for all the tests!

**Comment by jonathanslenders** [comment]
Thank you for this! Verified and merged in https://github.com/jonathanslenders/python-prompt-toolkit/commit/d4cd4f7c6ae6d2ca8304a3c54087b314de0b3755

**Comment by pombredanne** [comment]
:+1:

**Pull request closed without merging**
