### PR TITLE
Added accept_default argument to prompt().

### PR DESCRIPTION
**Pull request by jonathanslenders**

### CODE REVIEW

**Comment by asmeurer** [comment]
It doesn't seem to work with multiple consecutive prompts. For example:

```py
#!/usr/bin/env python
"""
Example of `accept_default`, a way to automatically accept the input that the
user typed without allowing him/her to edit it.

This should display the prompt with all the formatting like usual, but not
allow any editing.
"""
from __future__ import unicode_literals
from prompt_toolkit import PromptSession, HTML

P = PromptSession()

if __name__ == '__main__':
    answer = P.prompt(
        HTML('<b>Type <u>some input</u>: </b>'),
        accept_default=True, default='test')

    print('You said: %s' % answer)

    answer = P.prompt(
        HTML('<b>Type <u>some input</u>: </b>'),
        accept_default=True, default='test2')

    print('You said: %s' % answer)
```

It just prints

```
Type some input: test
You said: test
Type some input:
You said:
```

**Comment by asmeurer** [comment]
Is there some way to make the text not appear in the history?

**Comment by jonathanslenders** [comment]
No, not yet. I think that's a separate issue. It needs to be flexible enough so that Xonsh (for instance) can exclude commands that are prefixed with a space, like Bash.

**Comment by asmeurer** [comment]
Couldn't xonsh achieve that simply by subclassing the history class and filtering out the commands that should be filtered?

**Comment by beoboo** [comment]
I think the problem related to the default value not being shown in the second prompt is not related to the `accept_default` parameter: see #644

**Comment by asmeurer** [comment]
It works for me now, after I backported bae8e912edd6af44406ed6e9545fef75a98f6261 to my own accept handler. 

But I am also getting another exception. I'm not sure if it is related to this code. 

```pytb
Unhandled exception in event loop:
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.send(f.result())
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/application/run_in_terminal.py", line 98, in _run_in_t
    app._redraw()
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/application/application.py", line 436, in _redraw
    self.renderer.render(self, self.layout)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/renderer.py", line 545, in render
    ), parent_style='', erase_bg=False, z_index=None)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 288, in write_to_screen
    erase_bg, z_index)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 618, in write_to_screen
    screen, mouse_handlers, write_position, style, erase_bg, z_index)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 288, in write_to_screen
    erase_bg, z_index)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 2074, in write_to_screen
    screen, mouse_handlers, write_position, parent_style, erase_bg, z_index)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1392, in write_to_screen
    draw_func()
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1522, in _write_to_screen_at_index
    margin_screen = render_margin(m, width)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1512, in render_margin
    fragments = m.create_margin(self.render_info, width, write_position.height)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/margins.py", line 136, in create_margin
    return self.margin.create_margin(window_render_info, width, height)
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/layout/margins.py", line 249, in create_margin
    result.extend(to_formatted_text(get_continuation(width, y, y == last_y)))
  File "/Users/aaronmeurer/Documents/python-prompt-toolkit/prompt_toolkit/shortcuts/prompt.py", line 776, in _get_continuation
    prompt_continuation = prompt_continuation(width, line_number, is_soft_wrap)

Exception get_prompt_continuation() takes 2 positional arguments but 4 were given
```

**Comment by asmeurer** [comment]
And perhaps a meta-bug there, I can't escape the error message. It says "press ENTER" to continue, but then it just shows the error again. I have to kill the process. Maybe `Ctrl-C` should do a hard exit when this message is shown.

**Comment by asmeurer** [comment]
Ah, I didn't know about that change. It looks like [the docs](https://github.com/jonathanslenders/python-prompt-toolkit/blob/892f98e0cb9e9a04afc29065a9f9f6a5a3a5a728/prompt_toolkit/shortcuts/prompt.py#L209) weren't updated. 

What is the `is_soft_wrap` flag? For me if I type a really long line it applies to the first continuation prompt but not the rest. I know this is way off topic for this PR (which does seem to work just fine for me now), but I'm still hoping that https://github.com/jonathanslenders/python-prompt-toolkit/issues/493 can be implemented at some point (no soft wrapping at all).

**Comment by vdaskalov** [comment]
Hi Guys,

I like the default and accept_default parameters which were add because of this issue. I use this now for testing purposes.

However, is there easy way to suppress the std output of prompt_toolkit? This breaks my output when using nose.

Thanks

**Comment by vdaskalov** [comment]
Figured it out, needed to use DummyOutput

**Pull request merged**
